name: sample-gatsby
static_sites:
- build_command: yarn build
  environment_slug: gatsby
  github:
    branch: main
    deploy_on_push: true
    repo: digitalocean/sample-gatsby
  name: sample-gatsby
